feat: bump min deployment target to 11 for starscream 4.0.6
aws-amplify/aws-appsync-realtime-client-ios pull request #156
Opened 2024-03-11 20:06 UTC by lawmicha

*Issue #, if available:*

*Description of changes:*
Starscream's 4.0.6 dependency has min iOS 11 
https://github.com/daltoniam/Starscream/blob/4.0.6/Starscream.podspec
We'll bump this to the same

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-11 20:07 UTC, 5d submitted a review, later dismissed

2024-03-19 19:07 UTC, ruisebas requested changes
I think we should probably also update the **AppSyncRealTimeClient.xcodeproj** to set the deployment target to iOS 12, for consistency.

2024-04-23 00:11 UTC, 5d commented
As a similar PR #159 is merged to main, should we close this ticket?

2024-04-23 19:20 UTC, closed without merging

2024-04-23 19:20 UTC, lawmicha commented
> As a similar PR #159 is merged to main, should we close this ticket?

Right, this is no longer needed because #159 does the bump and starscream 4.0.8 as well